
apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
      - name: streamlit
        image: bijuthottathil/streamlit-postgres:latest
        ports:
        - containerPort: 8501
        env:
        - name: PGHOST
          value: "postgres-service"
        - name: PGDATABASE
          value: "postgres"
        - name: PGUSER
          value: "postgres"
        - name: PGPASSWORD
          value: "postgres"
